# Generated by Django 5.1.4 on 2024-12-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currency_rename_title_article_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('currency', models.CharField(max_length=250)),
                ('count', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('sum', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
