# Generated by Django 5.1.4 on 2024-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='count',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
