# Generated by Django 5.1.4 on 2024-12-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_count_alter_event_price_alter_event_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sum',
            new_name='transaction_sum',
        ),
    ]
